--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Dezembro-13-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALUGUEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ALUGUEL" 
   (	"DATA_RETIRADA" DATE, 
	"ID_BICICLETA" NUMBER(4,0), 
	"ID_USUARIO" NUMBER(2,0), 
	"PREVISAO_DEVOLUCAO" DATE, 
	"ID_FUNCIONARIO" NUMBER(3,0), 
	"ID_ALUGUEL" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BICICLETA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BICICLETA" 
   (	"ID_BICICLETA" NUMBER(4,0), 
	"STATUS" VARCHAR2(4 BYTE), 
	"PERIODO_MANUT" NUMBER(2,0), 
	"LOCAL_ATUAL" VARCHAR2(32 BYTE), 
	"PRECO_HORA" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTES" 
   (	"CPF" NUMBER(11,0), 
	"ID_USUARIO" NUMBER(3,0), 
	"NOME" VARCHAR2(30 BYTE), 
	"ENDERECO" VARCHAR2(50 BYTE), 
	"TELEFONE" NUMBER(8,0), 
	"DATA_NASC" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FUNCIONARIOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FUNCIONARIOS" 
   (	"ID_FUNCIONARIO" NUMBER(3,0), 
	"NOME_FUNC" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007065
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007065" ON "SYSTEM"."BICICLETA" ("ID_BICICLETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007053
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007053" ON "SYSTEM"."CLIENTES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007054
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007054" ON "SYSTEM"."CLIENTES" ("CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007056
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007056" ON "SYSTEM"."FUNCIONARIOS" ("ID_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger BICICLETA_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."BICICLETA_TRIGGER" 
    after update of id_bicicleta
    on aluguel declare
    aluguel a, bicicleta b
    begin
    update bicicleta SET status = 'ALU'
    where a.id_bicicleta = b.id_bicicleta
    end
/
ALTER TRIGGER "SYSTEM"."BICICLETA_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ALUGUEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ALUGUEL" MODIFY ("ID_ALUGUEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ALUGUEL" MODIFY ("ID_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ALUGUEL" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ALUGUEL" MODIFY ("ID_BICICLETA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ALUGUEL" MODIFY ("DATA_RETIRADA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BICICLETA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BICICLETA" ADD PRIMARY KEY ("ID_BICICLETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTES" ADD UNIQUE ("CPF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CLIENTES" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCIONARIOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FUNCIONARIOS" ADD UNIQUE ("ID_FUNCIONARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
